language: rust
dist: xenial

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6-dev
      - python3.6-venv

matrix:
  fast_finish: true
  include:
    - os: linux
      rust: nightly-2019-07-19

install:
  - python3.6 -m venv venv
  - source venv/bin/activate
  - pip install cffi virtualenv pytest
  - rustup default nightly-2019-07-19
  - rustup component add rustfmt
  - rustup component add clippy
  - travis_retry wget https://github.com/PyO3/maturin/releases/download/v0.7.2/maturin-v0.7.2-x86_64-unknown-linux-musl.tar.gz
  - tar -xzf maturin-v0.7.2-x86_64-unknown-linux-musl.tar.gz

script:
  - ci/linux.sh
